### ISSUE TITLE
Fails with 2 iterations

### ISSUE THREAD

**Issue by mgaitan** [mgaitan/miau#10]
The example "lo que tu quieras oir" fails as following 

```
(mvp_examples)tin@morochita:~/lab/miau/examples/lo_que_tu_quieras_oir$ miau Lo\ que\ tú\ Quieras\ Oír-12Z3J1uzd0Q.mp4 mensaje_original.txt -r remix_de_sofia.txt -o remix_de_sofia.mp3 --debug
[miau] 2017-05-13 01:06:56 INFO: Audio/Video:
   Lo que tú Quieras Oír-12Z3J1uzd0Q.mp4
Transcripts/subtitle:
   mensaje_original.txt
[miau] 2017-05-13 01:06:57 INFO: Fragmenting source. Iteration 1
[miau] 2017-05-13 01:06:57 DEBUG: Writing fragmented source to /tmp/tmpukowb3fd-iter1.txt
[miau] 2017-05-13 01:06:57 INFO: Fragmenting source. Iteration 2
[miau] 2017-05-13 01:06:57 DEBUG: Writing fragmented source to /tmp/tmp_2atpcu_-iter2.txt
[miau] 2017-05-13 01:06:57 INFO: Autodetected language for Lo que tú Quieras Oír-12Z3J1uzd0Q.mp4: es
[miau] 2017-05-13 01:06:57 INFO: Forcing aligment for Lo que tú Quieras Oír-12Z3J1uzd0Q.mp4 (step 1/2)
[miau] 2017-05-13 01:06:58 INFO: Forcing aligment for Lo que tú Quieras Oír-12Z3J1uzd0Q.mp4 (step 2/2)
[miau] 2017-05-13 01:06:59 DEBUG: Segments database written to /tmp/tmp1cfzg596.json
Traceback (most recent call last):
  File "/home/tin/lab/miau/miau.py", line 287, in miau
    remix_data = json.load(remix_fh)
  File "/usr/lib/python3.5/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tin/.virtualenvs/mvp_examples/bin/miau", line 11, in <module>
    load_entry_point('miau', 'console_scripts', 'miau')()
  File "/home/tin/lab/miau/miau.py", line 349, in main
    force_language=args['--lang']
  File "/home/tin/lab/miau/miau.py", line 300, in miau
    remix_data = [(l, fragments[l]) for l in remix_lines]
  File "/home/tin/lab/miau/miau.py", line 300, in <listcomp>
    remix_data = [(l, fragments[l]) for l in remix_lines]
KeyError: 'Sofía, soy Miguel.'
```

### Content of `/tmp/tmpukowb3fd-iter1.txt` 

```

Sofía,
soy Miguel.
Si estas en casa por favor coge el teléfono, es urgente que hablemos. No estas, 
Sofía,
dios, no sé cómo decirte esto. No, no voy a 
volver
a casa
, ni 
esta noche
ni ninguna otra. Es que...tú no te das cuenta pero 
necesito
que me des algo de tiempo ;Porque tengo que pensar aunque sé que pueda que no lo merezca, pero no quiero 
volver
. Tú no te das cuenta, estas con tus niños y tus plantas. 
Durante meses he pensado en
que podíamos intentar 
salvar lo nuestro
pero no es verdad. 
No quiero ser un inmaduro y lo he sido mucho tiempo por no decirte lo que pensaba.
Ahora creerás que soy un cerdo, claro yo lo pensaría. 
Pero
pronto 
habrás hecho tu vida al margen de mi.
Yo lo 
necesito
, 
necesito
marcharme, salir de esa casa. Ahora te echo de menos pero pasará, ya no 
te quiero.
No 
quiero salvar lo que queda de nosotros.
Siento no tener fuerza para decirte esto a la cara.
Pero
si lo hablamos me quedo...me quedo y no quiero quedarme.
```
### Content of `/tmp/tmp_2atpcu_-iter2.txt`

```
Sofía, soy Miguel. Si estas en casa por favor coge el teléfono, es urgente que hablemos. No estas, Sofía, dios, no sé cómo decirte esto. No, no voy a 
volver a casa,
ni esta noche ni ninguna otra. Es que...tú no te das cuenta pero necesito que me des algo de tiempo ;Porque tengo que pensar aunque sé que pueda que no lo merezca, pero no quiero volver. Tú no te das cuenta, estas con tus niños y tus plantas. Durante meses he pensado en que podíamos intentar salvar lo nuestro pero no es verdad. No quiero ser un inmaduro y lo he sido mucho tiempo por no decirte lo que pensaba. Ahora creerás que soy un cerdo, claro yo lo pensaría. Pero pronto habrás hecho tu vida al margen de mi. Yo lo necesito, necesito marcharme, salir de esa casa. Ahora te echo de menos pero pasará, ya no te quiero. No quiero salvar lo que queda de nosotros. Siento no tener fuerza para decirte esto a la cara. Pero si lo hablamos me quedo...me quedo y no quiero quedarme.
```

### Segment databse `/tmp/tmp1cfzg596.json`

```
{
  "": {
    "clip": "Lo que t\u00fa Quieras O\u00edr-12Z3J1uzd0Q.mp4",
    "end": 0.04,
    "begin": 0.0
  },
  "Sof\u00eda,": {
    "clip": "Lo que t\u00fa Quieras O\u00edr-12Z3J1uzd0Q.mp4",
    "end": 27.08,
    "begin": 26.72
  },
  "soy Miguel.": {
    "clip": "Lo que t\u00fa Quieras O\u00edr-12Z3J1uzd0Q.mp4",
    "end": 4.12,
    "begin": 2.12
  },
  "Si estas en casa por favor coge el tel\u00e9fono, es urgente que hablemos. No estas,": {
    "clip": "Lo que t\u00fa Quieras O\u00edr-12Z3J1uzd0Q.mp4",
    "end": 26.72,
    "begin": 4.12
  },
  "dios, no s\u00e9 c\u00f3mo decirte esto. No, no voy a": {
    "clip": "Lo que t\u00fa Quieras O\u00edr-12Z3J1uzd0Q.mp4",
    "end": 31.32,
    "begin": 27.08
  },
  "volver": {
    "clip": "Lo que t\u00fa Quieras O\u00edr-12Z3J1uzd0Q.mp4",
    "end": 64.8,
    "begin": 64.08
  },
  "a casa": {
    "clip": "Lo que t\u00fa Quieras O\u00edr-12Z3J1uzd0Q.mp4",
    "end": 34.16,
    "begin": 32.28
  },
  ", ni": {
    "clip": "Lo que t\u00fa Quieras O\u00edr-12Z3J1uzd0Q.mp4",
    "end": 34.52,
    "begin": 34.16
  },
  "esta noche": {
    "clip": "Lo que t\u00fa Quieras O\u00edr-12Z3J1uzd0Q.mp4",
    "end": 36.08,
    "begin": 34.52
  },
  "ni ninguna otra. Es que...t\u00fa no te das cuenta pero": {
    "clip": "Lo que t\u00fa Quieras O\u00edr-12Z3J1uzd0Q.mp4",
    "end": 46.12,
    "begin": 36.08
  },
  "necesito": {
    "clip": "Lo que t\u00fa Quieras O\u00edr-12Z3J1uzd0Q.mp4",
    "end": 121.56,
    "begin": 119.6
  },
  "que me des algo de tiempo ;Porque tengo que pensar aunque s\u00e9 que pueda que no lo merezca, pero no quiero": {
    "clip": "Lo que t\u00fa Quieras O\u00edr-12Z3J1uzd0Q.mp4",
    "end": 64.08,
    "begin": 47.44
  },
  ". T\u00fa no te das cuenta, estas con tus ni\u00f1os y tus plantas.": {
    "clip": "Lo que t\u00fa Quieras O\u00edr-12Z3J1uzd0Q.mp4",
    "end": 81.32,
    "begin": 64.8
  },
  "Durante meses he pensado en": {
    "clip": "Lo que t\u00fa Quieras O\u00edr-12Z3J1uzd0Q.mp4",
    "end": 84.68,
    "begin": 81.32
  },
  "que pod\u00edamos intentar": {
    "clip": "Lo que t\u00fa Quieras O\u00edr-12Z3J1uzd0Q.mp4",
    "end": 89.44,
    "begin": 84.68
  },
  "salvar lo nuestro": {
    "clip": "Lo que t\u00fa Quieras O\u00edr-12Z3J1uzd0Q.mp4",
    "end": 91.64,
    "begin": 89.44
  },
  "pero no es verdad.": {
    "clip": "Lo que t\u00fa Quieras O\u00edr-12Z3J1uzd0Q.mp4",
    "end": 93.32,
    "begin": 91.64
  },
  "No quiero ser un inmaduro y lo he sido mucho tiempo por no decirte lo que pensaba.": {
    "clip": "Lo que t\u00fa Quieras O\u00edr-12Z3J1uzd0Q.mp4",
    "end": 101.76,
    "begin": 93.32
  },
  "Ahora creer\u00e1s que soy un cerdo, claro yo lo pensar\u00eda.": {
    "clip": "Lo que t\u00fa Quieras O\u00edr-12Z3J1uzd0Q.mp4",
    "end": 105.4,
    "begin": 101.76
  },
  "Pero": {
    "clip": "Lo que t\u00fa Quieras O\u00edr-12Z3J1uzd0Q.mp4",
    "end": 203.44,
    "begin": 201.6
  },
  "pronto": {
    "clip": "Lo que t\u00fa Quieras O\u00edr-12Z3J1uzd0Q.mp4",
    "end": 109.08,
    "begin": 106.0
  },
  "habr\u00e1s hecho tu vida al margen de mi.": {
    "clip": "Lo que t\u00fa Quieras O\u00edr-12Z3J1uzd0Q.mp4",
    "end": 116.96,
    "begin": 109.08
  },
  "Yo lo": {
    "clip": "Lo que t\u00fa Quieras O\u00edr-12Z3J1uzd0Q.mp4",
    "end": 117.96,
    "begin": 116.96
  },
  ",": {
    "clip": "Lo que t\u00fa Quieras O\u00edr-12Z3J1uzd0Q.mp4",
    "end": 119.6,
    "begin": 118.96
  },
  "marcharme, salir de esa casa. Ahora te echo de menos pero pasar\u00e1, ya no": {
    "clip": "Lo que t\u00fa Quieras O\u00edr-12Z3J1uzd0Q.mp4",
    "end": 131.6,
    "begin": 121.56
  },
  "te quiero.": {
    "clip": "Lo que t\u00fa Quieras O\u00edr-12Z3J1uzd0Q.mp4",
    "end": 132.72,
    "begin": 131.6
  },
  "No": {
    "clip": "Lo que t\u00fa Quieras O\u00edr-12Z3J1uzd0Q.mp4",
    "end": 133.28,
    "begin": 132.72
  },
  "quiero salvar lo que queda de nosotros.": {
    "clip": "Lo que t\u00fa Quieras O\u00edr-12Z3J1uzd0Q.mp4",
    "end": 193.16,
    "begin": 133.28
  },
  "Siento no tener fuerza para decirte esto a la cara.": {
    "clip": "Lo que t\u00fa Quieras O\u00edr-12Z3J1uzd0Q.mp4",
    "end": 201.6,
    "begin": 193.16
  },
  "si lo hablamos me quedo...me quedo y no quiero quedarme.": {
    "clip": "Lo que t\u00fa Quieras O\u00edr-12Z3J1uzd0Q.mp4",
    "end": 220.6,
    "begin": 203.44
  },
  "Sof\u00eda, soy Miguel. Si estas en casa por favor coge el tel\u00e9fono, es urgente que hablemos. No estas, Sof\u00eda, dios, no s\u00e9 c\u00f3mo decirte esto. No, no voy a": {
    "clip": "Lo que t\u00fa Quieras O\u00edr-12Z3J1uzd0Q.mp4",
    "end": 34.28,
    "begin": 0.0
  },
  "volver a casa,": {
    "clip": "Lo que t\u00fa Quieras O\u00edr-12Z3J1uzd0Q.mp4",
    "end": 38.48,
    "begin": 34.28
  },
  "ni esta noche ni ninguna otra. Es que...t\u00fa no te das cuenta pero necesito que me des algo de tiempo ;Porque tengo que pensar aunque s\u00e9 que pueda que no lo merezca, pero no quiero volver. T\u00fa no te das cuenta, estas con tus ni\u00f1os y tus plantas. Durante meses he pensado en que pod\u00edamos intentar salvar lo nuestro pero no es verdad. No quiero ser un inmaduro y lo he sido mucho tiempo por no decirte lo que pensaba. Ahora creer\u00e1s que soy un cerdo, claro yo lo pensar\u00eda. Pero pronto habr\u00e1s hecho tu vida al margen de mi. Yo lo necesito, necesito marcharme, salir de esa casa. Ahora te echo de menos pero pasar\u00e1, ya no te quiero. No quiero salvar lo que queda de nosotros. Siento no tener fuerza para decirte esto a la cara. Pero si lo hablamos me quedo...me quedo y no quiero quedarme.": {
    "clip": "Lo que t\u00fa Quieras O\u00edr-12Z3J1uzd0Q.mp4",
    "end": 220.6,
    "begin": 38.48
  }
}
```

**Comment by gpavanb1** [comment]
I am unable to get this program to work for some videos I am trying and am getting the same issue for every one of them. Any chance this might be solved in the near future?

**Comment by mgaitan** [comment]
Hi @gpavanb1 ! I'm glad you try to use it. 
Of course, if there are is interest, I could try to take a look. 
A first step should be add some unitests, basically exposing this bug. 

are you able to code and interested in collaborate with this? 

thanks for contact me!
